version: '2'

services:

  root-ca-server:
    container_name: root-ca-server
    image: hyperledger/fabric-ca
    command: /usr/local/bin/fabric-ca-server start -b admin:adminpw
    volumes:
    - ./fabric-ca-server:/etc/hyperledger/fabric-ca-server
    ports:
      - 7054:7054

