version: '2'

services:
  orderer.up:
    container_name: orderer.up
    image: hyperledger/fabric-orderer
    environment:
      # - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP1
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./channel-artifacts/orderer.genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ./crypto-config/orderer/up.ca/orderers/orderer.up.ca/msp:/var/hyperledger/orderer/msp
    ports:
      - 7050:7050

  # couchdb0:
  #   container_name: couchdb0
  #   image: hyperledger/fabric-couchdb
  #   ports:
  #     - "5984:5984"
 
  peer0.org1.up:
    container_name: peer0.org1.up
    extends:
      file: base/peer-base-no-tls.yaml
      service: peer-base
    environment:
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=172.26.127.133:7051
      - CORE_PEER_ID=peer0
      - CORE_PEER_ADDRESS=peer0.org1.up:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      # - CORE_PEER_GOSSIP_BOOTSTRAP=101.231.114.238:7051
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.up.ca/peers/peer0.org1.up.ca/msp:/etc/hyperledger/fabric/msp
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer.up
      # - couchdb0
   
  cli.up:
    container_name: cli.up
    image: hyperledger/fabric-peer
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_PEER_ADDRESSAUTODETECT=false
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_NEXT=true
      - CORE_PEER_ID=cli.up
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_ADDRESS=peer0.org1.up:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.up.ca/users/Admin@org1.up.ca/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    #command: /bin/bash -c './scripts/script_yinlian.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    command: /bin/bash     
    volumes:
        - /var/run/:/host/var/run/
        - ./examples/:/opt/gopath/src/github.com/hyperledger/fabric/examples/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - peer0.org1.up


